# Generated by Django 5.0.6 on 2024-12-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DummyData",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("age", models.IntegerField()),
            ],
        ),
    ]
